// 由 App 的 AacData.kt 轉出——兩邊圖卡內容必須逐字一致，勿手改。
// 重新產生：見 docs/（parse AacData.kt）。

export const AAC_CATEGORIES = [
  { key:"products", id:"Products", emoji:"🛍" },
  { key:"food_drink", id:"FoodDrink", emoji:"🍽" },
  { key:"money", id:"Money", emoji:"💰" },
  { key:"actions", id:"Actions", emoji:"👋" },
  { key:"needs", id:"Needs", emoji:"🧩" },
  { key:"people", id:"People", emoji:"👥" },
  { key:"places", id:"Places", emoji:"📍" },
  { key:"medical", id:"Medical", emoji:"🏥" },
  { key:"time", id:"Time", emoji:"🕒" },
  { key:"questions", id:"Questions", emoji:"❓" },
  { key:"emotions", id:"Emotions", emoji:"💭" },
  { key:"emergency", id:"Emergency", emoji:"🚨" },
];

export const AAC_ITEMS = [
  { id:"p_baoyue", label:"包葉檳榔", emoji:"🌿", cat:"Products" },
  { id:"p_jingzai", label:"菁仔", emoji:"🥥", cat:"Products" },
  { id:"p_cig", label:"香菸", emoji:"🚬", cat:"Products" },
  { id:"p_lighter", label:"打火機", emoji:"🔥", cat:"Products" },
  { id:"p_bag", label:"袋子", emoji:"🛍", cat:"Products" },
  { id:"p_receipt", label:"發票", emoji:"🧾", cat:"Products" },
  { id:"p_menu", label:"菜單", emoji:"📋", cat:"Products" },
  { id:"p_ticket", label:"票券", emoji:"🎫", cat:"Products" },
  { id:"p_phone", label:"手機", emoji:"📱", cat:"Products" },
  { id:"p_key", label:"鑰匙", emoji:"🔑", cat:"Products" },
  { id:"p_wallet", label:"錢包", emoji:"👛", cat:"Products" },
  { id:"p_id", label:"證件", emoji:"🪪", cat:"Products" },
  { id:"p_card", label:"卡片", emoji:"💳", cat:"Products" },
  { id:"p_glasses", label:"眼鏡", emoji:"👓", cat:"Products" },
  { id:"p_cane", label:"拐杖", emoji:"🦯", cat:"Products" },
  { id:"p_wheelchair", label:"輪椅", emoji:"♿", cat:"Products" },
  { id:"p_charger", label:"充電器", emoji:"🔌", cat:"Products" },
  { id:"p_tissue", label:"衛生紙", emoji:"🧻", cat:"Products" },
  { id:"f_water_cup", label:"一杯水", emoji:"💧", cat:"FoodDrink" },
  { id:"f_want_water", label:"我要喝水", emoji:"💧", cat:"FoodDrink" },
  { id:"f_water_please", label:"請給我水", emoji:"🤲", cat:"FoodDrink" },
  { id:"f_warm_water_cup", label:"溫水一杯", emoji:"♨️", cat:"FoodDrink" },
  { id:"f_cold_water_cup", label:"冰水一杯", emoji:"🥤", cat:"FoodDrink" },
  { id:"f_water", label:"白開水", emoji:"💧", cat:"FoodDrink" },
  { id:"f_cold_water", label:"結冰水", emoji:"🥤", cat:"FoodDrink" },
  { id:"f_warm_water", label:"溫開水", emoji:"♨️", cat:"FoodDrink" },
  { id:"f_tea", label:"茶", emoji:"🍵", cat:"FoodDrink" },
  { id:"f_drink", label:"飲料", emoji:"🧃", cat:"FoodDrink" },
  { id:"f_coffee", label:"咖啡", emoji:"☕", cat:"FoodDrink" },
  { id:"f_meal", label:"餐點", emoji:"🍱", cat:"FoodDrink" },
  { id:"f_rice", label:"飯", emoji:"🍚", cat:"FoodDrink" },
  { id:"f_noodle", label:"麵", emoji:"🍜", cat:"FoodDrink" },
  { id:"f_soup", label:"湯", emoji:"🥣", cat:"FoodDrink" },
  { id:"f_fruit", label:"水果", emoji:"🍎", cat:"FoodDrink" },
  { id:"f_medicine_food", label:"配藥吃", emoji:"💊", cat:"FoodDrink" },
  { id:"f_bread", label:"麵包", emoji:"🍞", cat:"FoodDrink" },
  { id:"f_milk", label:"牛奶", emoji:"🥛", cat:"FoodDrink" },
  { id:"f_no_sugar", label:"無糖", emoji:"🚫", cat:"FoodDrink" },
  { id:"f_less_sugar", label:"少糖", emoji:"🍬", cat:"FoodDrink" },
  { id:"f_less_ice", label:"少冰", emoji:"🧊", cat:"FoodDrink" },
  { id:"f_hot", label:"熱的", emoji:"🔥", cat:"FoodDrink" },
  { id:"f_cold", label:"冰的", emoji:"❄️", cat:"FoodDrink" },
  { id:"f_straw", label:"吸管", emoji:"🥤", cat:"FoodDrink" },
  { id:"m_how_much", label:"多少錢", emoji:"💵", cat:"Money" },
  { id:"m_50", label:"$50", emoji:"💵", cat:"Money" },
  { id:"m_100", label:"$100", emoji:"💵", cat:"Money" },
  { id:"m_200", label:"$200", emoji:"💵", cat:"Money" },
  { id:"m_500", label:"$500", emoji:"💴", cat:"Money" },
  { id:"m_1000", label:"$1000", emoji:"💶", cat:"Money" },
  { id:"m_change", label:"找零", emoji:"🔁", cat:"Money" },
  { id:"m_1", label:"1 包", emoji:"1️⃣", cat:"Money" },
  { id:"m_2", label:"2 包", emoji:"2️⃣", cat:"Money" },
  { id:"m_3", label:"3 包", emoji:"3️⃣", cat:"Money" },
  { id:"m_1cup", label:"1 杯", emoji:"🥤", cat:"Money" },
  { id:"m_2cup", label:"2 杯", emoji:"🥤", cat:"Money" },
  { id:"m_cash", label:"現金", emoji:"💵", cat:"Money" },
  { id:"m_card", label:"刷卡", emoji:"💳", cat:"Money" },
  { id:"m_easycard", label:"悠遊卡", emoji:"💳", cat:"Money" },
  { id:"m_credit", label:"信用卡", emoji:"💳", cat:"Money" },
  { id:"m_debit", label:"金融卡", emoji:"🏧", cat:"Money" },
  { id:"m_mobile_pay", label:"行動支付", emoji:"📱", cat:"Money" },
  { id:"m_receipt", label:"收據", emoji:"🧾", cat:"Money" },
  { id:"m_tip", label:"小費", emoji:"💵", cat:"Money" },
  { id:"m_expensive", label:"太貴", emoji:"📈", cat:"Money" },
  { id:"a_give", label:"給您", emoji:"🤲", cat:"Actions" },
  { id:"a_ok", label:"收到", emoji:"👌", cat:"Actions" },
  { id:"a_wait", label:"等一下", emoji:"✋", cat:"Actions" },
  { id:"a_no", label:"沒有了", emoji:"🚫", cat:"Actions" },
  { id:"a_yes", label:"好", emoji:"✅", cat:"Actions" },
  { id:"a_takeaway", label:"帶走", emoji:"🥡", cat:"Actions" },
  { id:"a_dinein", label:"內用", emoji:"🍽", cat:"Actions" },
  { id:"a_open", label:"打開", emoji:"📂", cat:"Actions" },
  { id:"a_close", label:"關起來", emoji:"🔒", cat:"Actions" },
  { id:"a_call", label:"打電話", emoji:"📞", cat:"Actions" },
  { id:"a_write", label:"寫下來", emoji:"✍️", cat:"Actions" },
  { id:"a_repeat", label:"再說一次", emoji:"🔁", cat:"Actions" },
  { id:"a_slow", label:"慢一點", emoji:"🐢", cat:"Actions" },
  { id:"a_stop", label:"停一下", emoji:"🛑", cat:"Actions" },
  { id:"a_help_move", label:"扶我", emoji:"🧑‍🦽", cat:"Actions" },
  { id:"a_show", label:"請給我看", emoji:"👀", cat:"Actions" },
  { id:"a_choose", label:"幫我選", emoji:"☝️", cat:"Actions" },
  { id:"a_find", label:"幫我找", emoji:"🔎", cat:"Actions" },
  { id:"a_back", label:"我要回去", emoji:"↩️", cat:"Actions" },
  { id:"a_buy", label:"我要買", emoji:"🛒", cat:"Actions" },
  { id:"a_checkin", label:"我要報到", emoji:"📝", cat:"Actions" },
  { id:"n_toilet", label:"我要上廁所", emoji:"🚻", cat:"Needs" },
  { id:"n_rest", label:"我要休息", emoji:"🛏", cat:"Needs" },
  { id:"n_sleep", label:"想睡覺", emoji:"😴", cat:"Needs" },
  { id:"n_hot", label:"太熱", emoji:"🥵", cat:"Needs" },
  { id:"n_cold", label:"太冷", emoji:"🥶", cat:"Needs" },
  { id:"n_thirsty", label:"口渴", emoji:"💧", cat:"Needs" },
  { id:"n_hungry", label:"肚子餓", emoji:"🍚", cat:"Needs" },
  { id:"n_pain", label:"會痛", emoji:"⚡", cat:"Needs" },
  { id:"n_sit", label:"想坐下", emoji:"🪑", cat:"Needs" },
  { id:"n_stand", label:"想站起來", emoji:"🧍", cat:"Needs" },
  { id:"n_clean", label:"需要清潔", emoji:"🧼", cat:"Needs" },
  { id:"n_charge", label:"需要充電", emoji:"🔌", cat:"Needs" },
  { id:"n_quiet", label:"太吵", emoji:"🔇", cat:"Needs" },
  { id:"n_light", label:"太亮", emoji:"💡", cat:"Needs" },
  { id:"n_blanket", label:"需要毯子", emoji:"🧣", cat:"Needs" },
  { id:"n_tissue", label:"需要衛生紙", emoji:"🧻", cat:"Needs" },
  { id:"n_mask", label:"需要口罩", emoji:"😷", cat:"Needs" },
  { id:"n_wifi", label:"需要 Wi-Fi", emoji:"📶", cat:"Needs" },
  { id:"n_lost", label:"我迷路了", emoji:"🧭", cat:"Needs" },
  { id:"n_wait_family", label:"等家人", emoji:"👪", cat:"Needs" },
  { id:"pe_family", label:"家人", emoji:"👪", cat:"People" },
  { id:"pe_mom", label:"媽媽", emoji:"👩", cat:"People" },
  { id:"pe_dad", label:"爸爸", emoji:"👨", cat:"People" },
  { id:"pe_child", label:"小孩", emoji:"🧒", cat:"People" },
  { id:"pe_friend", label:"朋友", emoji:"🫂", cat:"People" },
  { id:"pe_doctor", label:"醫生", emoji:"🧑‍⚕️", cat:"People" },
  { id:"pe_nurse", label:"護理師", emoji:"👩‍⚕️", cat:"People" },
  { id:"pe_customer", label:"客人", emoji:"🧑", cat:"People" },
  { id:"pe_clerk", label:"店員", emoji:"🏪", cat:"People" },
  { id:"pe_driver", label:"司機", emoji:"🚕", cat:"People" },
  { id:"pe_teacher", label:"老師", emoji:"🏫", cat:"People" },
  { id:"pe_police", label:"警察", emoji:"👮", cat:"People" },
  { id:"pe_staff", label:"服務人員", emoji:"ℹ️", cat:"People" },
  { id:"pe_interpreter", label:"翻譯員", emoji:"🌐", cat:"People" },
  { id:"pe_caregiver", label:"照護員", emoji:"🤲", cat:"People" },
  { id:"pe_pharmacist", label:"藥師", emoji:"💊", cat:"People" },
  { id:"pl_home", label:"家裡", emoji:"🏠", cat:"Places" },
  { id:"pl_shop", label:"店裡", emoji:"🏪", cat:"Places" },
  { id:"pl_hospital", label:"醫院", emoji:"🏥", cat:"Places" },
  { id:"pl_clinic", label:"診所", emoji:"🏨", cat:"Places" },
  { id:"pl_pharmacy", label:"藥局", emoji:"💊", cat:"Places" },
  { id:"pl_toilet", label:"廁所", emoji:"🚻", cat:"Places" },
  { id:"pl_restaurant", label:"餐廳", emoji:"🍽", cat:"Places" },
  { id:"pl_station", label:"車站", emoji:"🚉", cat:"Places" },
  { id:"pl_car", label:"車上", emoji:"🚗", cat:"Places" },
  { id:"pl_outside", label:"外面", emoji:"🌤", cat:"Places" },
  { id:"pl_airport", label:"機場", emoji:"✈️", cat:"Places" },
  { id:"pl_parking", label:"停車場", emoji:"🅿️", cat:"Places" },
  { id:"pl_bank", label:"銀行", emoji:"🏦", cat:"Places" },
  { id:"pl_post", label:"郵局", emoji:"📮", cat:"Places" },
  { id:"pl_school", label:"學校", emoji:"🏫", cat:"Places" },
  { id:"pl_library", label:"圖書館", emoji:"📚", cat:"Places" },
  { id:"pl_hotel", label:"旅館", emoji:"🏨", cat:"Places" },
  { id:"pl_gate", label:"登機門", emoji:"🚪", cat:"Places" },
  { id:"md_sick", label:"不舒服", emoji:"🤕", cat:"Medical", strong:true },
  { id:"md_pain_head", label:"頭痛", emoji:"🤯", cat:"Medical" },
  { id:"md_pain_chest", label:"胸口痛", emoji:"💔", cat:"Medical", strong:true },
  { id:"md_dizzy", label:"頭暈", emoji:"😵", cat:"Medical" },
  { id:"md_nausea", label:"想吐", emoji:"🤢", cat:"Medical" },
  { id:"md_breath", label:"喘不過氣", emoji:"🫁", cat:"Medical", strong:true },
  { id:"md_medicine", label:"需要藥", emoji:"💊", cat:"Medical" },
  { id:"md_hospital", label:"去醫院", emoji:"🚑", cat:"Medical", strong:true },
  { id:"md_pressure", label:"量血壓", emoji:"🩺", cat:"Medical" },
  { id:"md_sugar", label:"量血糖", emoji:"🩸", cat:"Medical" },
  { id:"md_allergy", label:"過敏", emoji:"🤧", cat:"Medical" },
  { id:"md_diabetes", label:"糖尿病", emoji:"🩸", cat:"Medical" },
  { id:"md_heart", label:"心臟不舒服", emoji:"💔", cat:"Medical", strong:true },
  { id:"md_fever", label:"發燒", emoji:"🌡", cat:"Medical" },
  { id:"md_fall", label:"跌倒", emoji:"🩹", cat:"Medical", strong:true },
  { id:"md_appointment", label:"預約", emoji:"📅", cat:"Medical" },
  { id:"md_insurance", label:"保險卡", emoji:"🪪", cat:"Medical" },
  { id:"md_prescription", label:"處方箋", emoji:"📄", cat:"Medical" },
  { id:"t_now", label:"現在", emoji:"⏱", cat:"Time" },
  { id:"t_later", label:"等一下", emoji:"⏳", cat:"Time" },
  { id:"t_morning", label:"早上", emoji:"🌅", cat:"Time" },
  { id:"t_noon", label:"中午", emoji:"☀️", cat:"Time" },
  { id:"t_evening", label:"晚上", emoji:"🌙", cat:"Time" },
  { id:"t_today", label:"今天", emoji:"📅", cat:"Time" },
  { id:"t_tomorrow", label:"明天", emoji:"➡️", cat:"Time" },
  { id:"t_yesterday", label:"昨天", emoji:"⬅️", cat:"Time" },
  { id:"t_min5", label:"5 分鐘", emoji:"5️⃣", cat:"Time" },
  { id:"t_min10", label:"10 分鐘", emoji:"🔟", cat:"Time" },
  { id:"t_min30", label:"30 分鐘", emoji:"🕧", cat:"Time" },
  { id:"t_hour1", label:"1 小時", emoji:"🕐", cat:"Time" },
  { id:"t_before", label:"之前", emoji:"⬅️", cat:"Time" },
  { id:"t_after", label:"之後", emoji:"➡️", cat:"Time" },
  { id:"t_medicine_time", label:"吃藥時間", emoji:"💊", cat:"Time" },
  { id:"t_checkout", label:"退房時間", emoji:"🏨", cat:"Time" },
  { id:"q_where", label:"在哪裡？", emoji:"📍", cat:"Questions" },
  { id:"q_when", label:"什麼時候？", emoji:"🕒", cat:"Questions" },
  { id:"q_how", label:"怎麼做？", emoji:"❓", cat:"Questions" },
  { id:"q_can", label:"可以嗎？", emoji:"✅", cat:"Questions" },
  { id:"q_have", label:"有嗎？", emoji:"🔎", cat:"Questions" },
  { id:"q_price", label:"多少錢？", emoji:"💵", cat:"Questions" },
  { id:"q_again", label:"可以再說一次嗎？", emoji:"🔁", cat:"Questions" },
  { id:"q_help", label:"可以幫我嗎？", emoji:"🤲", cat:"Questions" },
  { id:"q_toilet", label:"廁所在哪裡？", emoji:"🚻", cat:"Questions" },
  { id:"q_exit", label:"出口在哪裡？", emoji:"🚪", cat:"Questions" },
  { id:"q_counter", label:"服務台在哪裡？", emoji:"ℹ️", cat:"Questions" },
  { id:"q_gate", label:"登機門在哪裡？", emoji:"✈️", cat:"Questions" },
  { id:"q_appointment", label:"要等多久？", emoji:"⏳", cat:"Questions" },
  { id:"q_english", label:"可以說中文嗎？", emoji:"🌐", cat:"Questions" },
  { id:"e_thanks", label:"謝謝", emoji:"🙏", cat:"Emotions" },
  { id:"e_sorry", label:"抱歉", emoji:"😅", cat:"Emotions" },
  { id:"e_welcome", label:"歡迎光臨", emoji:"😊", cat:"Emotions" },
  { id:"e_happy", label:"開心", emoji:"😊", cat:"Emotions" },
  { id:"e_worried", label:"擔心", emoji:"😟", cat:"Emotions" },
  { id:"e_angry", label:"生氣", emoji:"😠", cat:"Emotions" },
  { id:"e_tired", label:"很累", emoji:"😮‍💨", cat:"Emotions" },
  { id:"e_scared", label:"害怕", emoji:"😨", cat:"Emotions" },
  { id:"e_good", label:"很好", emoji:"👍", cat:"Emotions" },
  { id:"e_bad", label:"不好", emoji:"👎", cat:"Emotions" },
  { id:"e_comfort", label:"沒關係", emoji:"🤝", cat:"Emotions" },
  { id:"e_confused", label:"我聽不懂", emoji:"😕", cat:"Emotions" },
  { id:"e_nervous", label:"緊張", emoji:"😰", cat:"Emotions" },
  { id:"e_lonely", label:"孤單", emoji:"🥺", cat:"Emotions" },
  { id:"e_safe", label:"安心", emoji:"😌", cat:"Emotions" },
  { id:"e_hurry", label:"很急", emoji:"🏃", cat:"Emotions" },
  { id:"g_help", label:"救命", emoji:"🆘", cat:"Emergency", strong:true },
  { id:"g_family", label:"找家人", emoji:"📞", cat:"Emergency", strong:true },
  { id:"g_sick", label:"不舒服", emoji:"🤕", cat:"Emergency", strong:true },
  { id:"g_police", label:"報警", emoji:"🚓", cat:"Emergency", strong:true },
  { id:"g_ambulance", label:"叫救護車", emoji:"🚑", cat:"Emergency", strong:true },
  { id:"g_fall", label:"跌倒了", emoji:"🩹", cat:"Emergency", strong:true },
  { id:"g_choke", label:"噎到", emoji:"🫢", cat:"Emergency", strong:true },
  { id:"g_fire", label:"火災", emoji:"🔥", cat:"Emergency", strong:true },
  { id:"g_lost", label:"迷路", emoji:"🧭", cat:"Emergency", strong:true },
  { id:"g_cant_breathe", label:"不能呼吸", emoji:"🫁", cat:"Emergency", strong:true },
  { id:"g_seizure", label:"抽搐", emoji:"⚠️", cat:"Emergency", strong:true },
  { id:"g_allergy", label:"嚴重過敏", emoji:"🤧", cat:"Emergency", strong:true },
  { id:"g_chest", label:"胸痛", emoji:"💔", cat:"Emergency", strong:true },
];

export const CURRENCIES = [
  { code:"NTD", symbol:"NT$", name:"新台幣" },
  { code:"USD", symbol:"US$", name:"美元" },
  { code:"JPY", symbol:"¥", name:"日圓" },
  { code:"KRW", symbol:"₩", name:"韓圜" },
  { code:"CNY", symbol:"¥", name:"人民幣" },
  { code:"EUR", symbol:"€", name:"歐元" },
];
