// AAC 圖卡資料：分類、216 張卡、幣別。卡片本身由 App 的 AacData.kt 轉出。
//
// label 保留繁中原文，是**演算法的比對基準**——排序引擎的概念詞群（水／食／藥…）
// 是用中文策劃的，靠它做語意相似；換成譯文會整組失效。畫面顯示與朗讀一律走
// i18n 裡對應語言的詞面，兩者分開，互不影響。
export const AAC_CATEGORIES = [
  { key:"products", id:"Products", emoji:"🛍" },
  { key:"food_drink", id:"FoodDrink", emoji:"🍽" },
  { key:"money", id:"Money", emoji:"💰" },
  { key:"actions", id:"Actions", emoji:"👋" },
  { key:"needs", id:"Needs", emoji:"🧩" },
  { key:"people", id:"People", emoji:"👥" },
  { key:"places", id:"Places", emoji:"📍" },
  { key:"medical", id:"Medical", emoji:"🏥" },
  { key:"time", id:"Time", emoji:"🕒" },
  { key:"questions", id:"Questions", emoji:"❓" },
  { key:"emotions", id:"Emotions", emoji:"💭" },
  { key:"emergency", id:"Emergency", emoji:"🚨" },
];

export const AAC_ITEMS = [
  { id:"p_baoyue", label:"包葉檳榔", emoji:"🌿", cat:"Products", i18n:{ en:"Betel (leaf)", ja:"包み葉ビンロウ", ko:"잎 빈랑" } },
  { id:"p_jingzai", label:"菁仔", emoji:"🥥", cat:"Products", i18n:{ en:"Betel (plain)", ja:"ビンロウ（素）", ko:"생 빈랑" } },
  { id:"p_cig", label:"香菸", emoji:"🚬", cat:"Products", i18n:{ en:"Cigarettes", ja:"タバコ", ko:"담배" } },
  { id:"p_lighter", label:"打火機", emoji:"🔥", cat:"Products", i18n:{ en:"Lighter", ja:"ライター", ko:"라이터" } },
  { id:"p_bag", label:"袋子", emoji:"🛍", cat:"Products", i18n:{ en:"Bag", ja:"袋", ko:"봉지" } },
  { id:"p_receipt", label:"發票", emoji:"🧾", cat:"Products", i18n:{ en:"Invoice", ja:"レシート", ko:"영수증" } },
  { id:"p_menu", label:"菜單", emoji:"📋", cat:"Products", i18n:{ en:"Menu", ja:"メニュー", ko:"메뉴" } },
  { id:"p_ticket", label:"票券", emoji:"🎫", cat:"Products", i18n:{ en:"Ticket", ja:"チケット", ko:"티켓" } },
  { id:"p_phone", label:"手機", emoji:"📱", cat:"Products", i18n:{ en:"Phone", ja:"スマホ", ko:"휴대폰" } },
  { id:"p_key", label:"鑰匙", emoji:"🔑", cat:"Products", i18n:{ en:"Keys", ja:"鍵", ko:"열쇠" } },
  { id:"p_wallet", label:"錢包", emoji:"👛", cat:"Products", i18n:{ en:"Wallet", ja:"財布", ko:"지갑" } },
  { id:"p_id", label:"證件", emoji:"🪪", cat:"Products", i18n:{ en:"ID", ja:"身分証", ko:"신분증" } },
  { id:"p_card", label:"卡片", emoji:"💳", cat:"Products", i18n:{ en:"Card", ja:"カード", ko:"카드" } },
  { id:"p_glasses", label:"眼鏡", emoji:"👓", cat:"Products", i18n:{ en:"Glasses", ja:"メガネ", ko:"안경" } },
  { id:"p_cane", label:"拐杖", emoji:"🦯", cat:"Products", i18n:{ en:"Cane", ja:"杖", ko:"지팡이" } },
  { id:"p_wheelchair", label:"輪椅", emoji:"♿", cat:"Products", i18n:{ en:"Wheelchair", ja:"車いす", ko:"휠체어" } },
  { id:"p_charger", label:"充電器", emoji:"🔌", cat:"Products", i18n:{ en:"Charger", ja:"充電器", ko:"충전기" } },
  { id:"p_tissue", label:"衛生紙", emoji:"🧻", cat:"Products", i18n:{ en:"Tissue", ja:"ティッシュ", ko:"휴지" } },
  { id:"f_water_cup", label:"一杯水", emoji:"💧", cat:"FoodDrink", i18n:{ en:"A glass of water", ja:"水一杯", ko:"물 한 잔" } },
  { id:"f_want_water", label:"我要喝水", emoji:"💧", cat:"FoodDrink", i18n:{ en:"I want water", ja:"水が飲みたい", ko:"물 마시고 싶어요" } },
  { id:"f_water_please", label:"請給我水", emoji:"🤲", cat:"FoodDrink", i18n:{ en:"Water, please", ja:"水をください", ko:"물 주세요" } },
  { id:"f_warm_water_cup", label:"溫水一杯", emoji:"♨️", cat:"FoodDrink", i18n:{ en:"Warm water, a cup", ja:"ぬるま湯一杯", ko:"미온수 한 잔" } },
  { id:"f_cold_water_cup", label:"冰水一杯", emoji:"🥤", cat:"FoodDrink", i18n:{ en:"Ice water, a cup", ja:"氷水一杯", ko:"얼음물 한 잔" } },
  { id:"f_water", label:"白開水", emoji:"💧", cat:"FoodDrink", i18n:{ en:"Plain water", ja:"お水", ko:"맹물" } },
  { id:"f_cold_water", label:"結冰水", emoji:"🥤", cat:"FoodDrink", i18n:{ en:"Iced water", ja:"氷水", ko:"얼음물" } },
  { id:"f_warm_water", label:"溫開水", emoji:"♨️", cat:"FoodDrink", i18n:{ en:"Warm water", ja:"ぬるま湯", ko:"미온수" } },
  { id:"f_tea", label:"茶", emoji:"🍵", cat:"FoodDrink", i18n:{ en:"Tea", ja:"お茶", ko:"차" } },
  { id:"f_drink", label:"飲料", emoji:"🧃", cat:"FoodDrink", i18n:{ en:"Drink", ja:"飲み物", ko:"음료" } },
  { id:"f_coffee", label:"咖啡", emoji:"☕", cat:"FoodDrink", i18n:{ en:"Coffee", ja:"コーヒー", ko:"커피" } },
  { id:"f_meal", label:"餐點", emoji:"🍱", cat:"FoodDrink", i18n:{ en:"Meal", ja:"食事", ko:"식사" } },
  { id:"f_rice", label:"飯", emoji:"🍚", cat:"FoodDrink", i18n:{ en:"Rice", ja:"ごはん", ko:"밥" } },
  { id:"f_noodle", label:"麵", emoji:"🍜", cat:"FoodDrink", i18n:{ en:"Noodles", ja:"麺", ko:"면" } },
  { id:"f_soup", label:"湯", emoji:"🥣", cat:"FoodDrink", i18n:{ en:"Soup", ja:"スープ", ko:"국" } },
  { id:"f_fruit", label:"水果", emoji:"🍎", cat:"FoodDrink", i18n:{ en:"Fruit", ja:"果物", ko:"과일" } },
  { id:"f_medicine_food", label:"配藥吃", emoji:"💊", cat:"FoodDrink", i18n:{ en:"Take with meds", ja:"薬と一緒に", ko:"약과 함께" } },
  { id:"f_bread", label:"麵包", emoji:"🍞", cat:"FoodDrink", i18n:{ en:"Bread", ja:"パン", ko:"빵" } },
  { id:"f_milk", label:"牛奶", emoji:"🥛", cat:"FoodDrink", i18n:{ en:"Milk", ja:"牛乳", ko:"우유" } },
  { id:"f_no_sugar", label:"無糖", emoji:"🚫", cat:"FoodDrink", i18n:{ en:"No sugar", ja:"砂糖なし", ko:"무설탕" } },
  { id:"f_less_sugar", label:"少糖", emoji:"🍬", cat:"FoodDrink", i18n:{ en:"Less sugar", ja:"砂糖少なめ", ko:"설탕 적게" } },
  { id:"f_less_ice", label:"少冰", emoji:"🧊", cat:"FoodDrink", i18n:{ en:"Less ice", ja:"氷少なめ", ko:"얼음 적게" } },
  { id:"f_hot", label:"熱的", emoji:"🔥", cat:"FoodDrink", i18n:{ en:"Hot", ja:"ホット", ko:"뜨겁게" } },
  { id:"f_cold", label:"冰的", emoji:"❄️", cat:"FoodDrink", i18n:{ en:"Cold", ja:"冷たい", ko:"차갑게" } },
  { id:"f_straw", label:"吸管", emoji:"🥤", cat:"FoodDrink", i18n:{ en:"Straw", ja:"ストロー", ko:"빨대" } },
  { id:"m_how_much", label:"多少錢", emoji:"💵", cat:"Money", i18n:{ en:"How much?", ja:"いくら？", ko:"얼마예요?" } },
  { id:"m_50", label:"$50", emoji:"💵", cat:"Money", i18n:{ en:"$50", ja:"$50", ko:"$50" } },
  { id:"m_100", label:"$100", emoji:"💵", cat:"Money", i18n:{ en:"$100", ja:"$100", ko:"$100" } },
  { id:"m_200", label:"$200", emoji:"💵", cat:"Money", i18n:{ en:"$200", ja:"$200", ko:"$200" } },
  { id:"m_500", label:"$500", emoji:"💴", cat:"Money", i18n:{ en:"$500", ja:"$500", ko:"$500" } },
  { id:"m_1000", label:"$1000", emoji:"💶", cat:"Money", i18n:{ en:"$1000", ja:"$1000", ko:"$1000" } },
  { id:"m_change", label:"找零", emoji:"🔁", cat:"Money", i18n:{ en:"Change", ja:"おつり", ko:"거스름돈" } },
  { id:"m_1", label:"1 包", emoji:"1️⃣", cat:"Money", i18n:{ en:"1 pack", ja:"1袋", ko:"1봉지" } },
  { id:"m_2", label:"2 包", emoji:"2️⃣", cat:"Money", i18n:{ en:"2 packs", ja:"2袋", ko:"2봉지" } },
  { id:"m_3", label:"3 包", emoji:"3️⃣", cat:"Money", i18n:{ en:"3 packs", ja:"3袋", ko:"3봉지" } },
  { id:"m_1cup", label:"1 杯", emoji:"🥤", cat:"Money", i18n:{ en:"1 cup", ja:"1杯", ko:"1잔" } },
  { id:"m_2cup", label:"2 杯", emoji:"🥤", cat:"Money", i18n:{ en:"2 cups", ja:"2杯", ko:"2잔" } },
  { id:"m_cash", label:"現金", emoji:"💵", cat:"Money", i18n:{ en:"Cash", ja:"現金", ko:"현금" } },
  { id:"m_card", label:"刷卡", emoji:"💳", cat:"Money", i18n:{ en:"Card payment", ja:"カード払い", ko:"카드 결제" } },
  { id:"m_easycard", label:"悠遊卡", emoji:"💳", cat:"Money", i18n:{ en:"EasyCard", ja:"悠遊カード", ko:"이지카드" } },
  { id:"m_credit", label:"信用卡", emoji:"💳", cat:"Money", i18n:{ en:"Credit card", ja:"クレジットカード", ko:"신용카드" } },
  { id:"m_debit", label:"金融卡", emoji:"🏧", cat:"Money", i18n:{ en:"Debit card", ja:"デビットカード", ko:"체크카드" } },
  { id:"m_mobile_pay", label:"行動支付", emoji:"📱", cat:"Money", i18n:{ en:"Mobile pay", ja:"モバイル決済", ko:"모바일 결제" } },
  { id:"m_receipt", label:"收據", emoji:"🧾", cat:"Money", i18n:{ en:"Receipt", ja:"レシート", ko:"영수증" } },
  { id:"m_tip", label:"小費", emoji:"💵", cat:"Money", i18n:{ en:"Tip", ja:"チップ", ko:"팁" } },
  { id:"m_expensive", label:"太貴", emoji:"📈", cat:"Money", i18n:{ en:"Too expensive", ja:"高すぎる", ko:"너무 비싸요" } },
  { id:"a_give", label:"給您", emoji:"🤲", cat:"Actions", i18n:{ en:"Here you go", ja:"どうぞ", ko:"여기요" } },
  { id:"a_ok", label:"收到", emoji:"👌", cat:"Actions", i18n:{ en:"Got it", ja:"了解", ko:"알겠어요" } },
  { id:"a_wait", label:"等一下", emoji:"✋", cat:"Actions", i18n:{ en:"Wait a moment", ja:"ちょっと待って", ko:"잠깐만요" } },
  { id:"a_no", label:"沒有了", emoji:"🚫", cat:"Actions", i18n:{ en:"All out", ja:"もうない", ko:"다 떨어졌어요" } },
  { id:"a_yes", label:"好", emoji:"✅", cat:"Actions", i18n:{ en:"OK", ja:"いいよ", ko:"좋아요" } },
  { id:"a_takeaway", label:"帶走", emoji:"🥡", cat:"Actions", i18n:{ en:"Take away", ja:"持ち帰り", ko:"포장" } },
  { id:"a_dinein", label:"內用", emoji:"🍽", cat:"Actions", i18n:{ en:"Eat in", ja:"店内", ko:"매장" } },
  { id:"a_open", label:"打開", emoji:"📂", cat:"Actions", i18n:{ en:"Open it", ja:"開けて", ko:"열어 주세요" } },
  { id:"a_close", label:"關起來", emoji:"🔒", cat:"Actions", i18n:{ en:"Close it", ja:"閉めて", ko:"닫아 주세요" } },
  { id:"a_call", label:"打電話", emoji:"📞", cat:"Actions", i18n:{ en:"Make a call", ja:"電話する", ko:"전화해요" } },
  { id:"a_write", label:"寫下來", emoji:"✍️", cat:"Actions", i18n:{ en:"Write it down", ja:"書いて", ko:"적어 주세요" } },
  { id:"a_repeat", label:"再說一次", emoji:"🔁", cat:"Actions", i18n:{ en:"Say it again", ja:"もう一度", ko:"다시 말해 주세요" } },
  { id:"a_slow", label:"慢一點", emoji:"🐢", cat:"Actions", i18n:{ en:"Slower", ja:"ゆっくり", ko:"천천히" } },
  { id:"a_stop", label:"停一下", emoji:"🛑", cat:"Actions", i18n:{ en:"Stop a moment", ja:"止めて", ko:"잠깐 멈춰요" } },
  { id:"a_help_move", label:"扶我", emoji:"🧑‍🦽", cat:"Actions", i18n:{ en:"Help me up", ja:"支えて", ko:"부축해 주세요" } },
  { id:"a_show", label:"請給我看", emoji:"👀", cat:"Actions", i18n:{ en:"Show me", ja:"見せて", ko:"보여 주세요" } },
  { id:"a_choose", label:"幫我選", emoji:"☝️", cat:"Actions", i18n:{ en:"Choose for me", ja:"選んで", ko:"골라 주세요" } },
  { id:"a_find", label:"幫我找", emoji:"🔎", cat:"Actions", i18n:{ en:"Find it for me", ja:"探して", ko:"찾아 주세요" } },
  { id:"a_back", label:"我要回去", emoji:"↩️", cat:"Actions", i18n:{ en:"I want to go back", ja:"帰りたい", ko:"돌아가고 싶어요" } },
  { id:"a_buy", label:"我要買", emoji:"🛒", cat:"Actions", i18n:{ en:"I want to buy", ja:"買いたい", ko:"사고 싶어요" } },
  { id:"a_checkin", label:"我要報到", emoji:"📝", cat:"Actions", i18n:{ en:"I'm checking in", ja:"受付します", ko:"접수할게요" } },
  { id:"n_toilet", label:"我要上廁所", emoji:"🚻", cat:"Needs", i18n:{ en:"I need the toilet", ja:"トイレに行きたい", ko:"화장실 가고 싶어요" } },
  { id:"n_rest", label:"我要休息", emoji:"🛏", cat:"Needs", i18n:{ en:"I need to rest", ja:"休みたい", ko:"쉬고 싶어요" } },
  { id:"n_sleep", label:"想睡覺", emoji:"😴", cat:"Needs", i18n:{ en:"Sleepy", ja:"眠い", ko:"졸려요" } },
  { id:"n_hot", label:"太熱", emoji:"🥵", cat:"Needs", i18n:{ en:"Too hot", ja:"暑すぎる", ko:"너무 더워요" } },
  { id:"n_cold", label:"太冷", emoji:"🥶", cat:"Needs", i18n:{ en:"Too cold", ja:"寒すぎる", ko:"너무 추워요" } },
  { id:"n_thirsty", label:"口渴", emoji:"💧", cat:"Needs", i18n:{ en:"Thirsty", ja:"のどが渇いた", ko:"목말라요" } },
  { id:"n_hungry", label:"肚子餓", emoji:"🍚", cat:"Needs", i18n:{ en:"Hungry", ja:"お腹すいた", ko:"배고파요" } },
  { id:"n_pain", label:"會痛", emoji:"⚡", cat:"Needs", i18n:{ en:"It hurts", ja:"痛い", ko:"아파요" } },
  { id:"n_sit", label:"想坐下", emoji:"🪑", cat:"Needs", i18n:{ en:"Want to sit", ja:"座りたい", ko:"앉고 싶어요" } },
  { id:"n_stand", label:"想站起來", emoji:"🧍", cat:"Needs", i18n:{ en:"Want to stand", ja:"立ちたい", ko:"일어서고 싶어요" } },
  { id:"n_clean", label:"需要清潔", emoji:"🧼", cat:"Needs", i18n:{ en:"Need cleaning", ja:"掃除がいる", ko:"청소가 필요해요" } },
  { id:"n_charge", label:"需要充電", emoji:"🔌", cat:"Needs", i18n:{ en:"Need charging", ja:"充電したい", ko:"충전이 필요해요" } },
  { id:"n_quiet", label:"太吵", emoji:"🔇", cat:"Needs", i18n:{ en:"Too noisy", ja:"うるさい", ko:"너무 시끄러워요" } },
  { id:"n_light", label:"太亮", emoji:"💡", cat:"Needs", i18n:{ en:"Too bright", ja:"まぶしい", ko:"너무 밝아요" } },
  { id:"n_blanket", label:"需要毯子", emoji:"🧣", cat:"Needs", i18n:{ en:"Need a blanket", ja:"毛布がほしい", ko:"담요가 필요해요" } },
  { id:"n_tissue", label:"需要衛生紙", emoji:"🧻", cat:"Needs", i18n:{ en:"Need tissue", ja:"ティッシュがほしい", ko:"휴지가 필요해요" } },
  { id:"n_mask", label:"需要口罩", emoji:"😷", cat:"Needs", i18n:{ en:"Need a mask", ja:"マスクがほしい", ko:"마스크가 필요해요" } },
  { id:"n_wifi", label:"需要 Wi-Fi", emoji:"📶", cat:"Needs", i18n:{ en:"Need Wi-Fi", ja:"Wi-Fiがほしい", ko:"Wi-Fi가 필요해요" } },
  { id:"n_lost", label:"我迷路了", emoji:"🧭", cat:"Needs", i18n:{ en:"I'm lost", ja:"道に迷った", ko:"길을 잃었어요" } },
  { id:"n_wait_family", label:"等家人", emoji:"👪", cat:"Needs", i18n:{ en:"Waiting for family", ja:"家族を待つ", ko:"가족을 기다려요" } },
  { id:"pe_family", label:"家人", emoji:"👪", cat:"People", i18n:{ en:"Family", ja:"家族", ko:"가족" } },
  { id:"pe_mom", label:"媽媽", emoji:"👩", cat:"People", i18n:{ en:"Mom", ja:"お母さん", ko:"엄마" } },
  { id:"pe_dad", label:"爸爸", emoji:"👨", cat:"People", i18n:{ en:"Dad", ja:"お父さん", ko:"아빠" } },
  { id:"pe_child", label:"小孩", emoji:"🧒", cat:"People", i18n:{ en:"Child", ja:"子ども", ko:"아이" } },
  { id:"pe_friend", label:"朋友", emoji:"🫂", cat:"People", i18n:{ en:"Friend", ja:"友だち", ko:"친구" } },
  { id:"pe_doctor", label:"醫生", emoji:"🧑‍⚕️", cat:"People", i18n:{ en:"Doctor", ja:"医師", ko:"의사" } },
  { id:"pe_nurse", label:"護理師", emoji:"👩‍⚕️", cat:"People", i18n:{ en:"Nurse", ja:"看護師", ko:"간호사" } },
  { id:"pe_customer", label:"客人", emoji:"🧑", cat:"People", i18n:{ en:"Customer", ja:"お客さん", ko:"손님" } },
  { id:"pe_clerk", label:"店員", emoji:"🏪", cat:"People", i18n:{ en:"Clerk", ja:"店員", ko:"점원" } },
  { id:"pe_driver", label:"司機", emoji:"🚕", cat:"People", i18n:{ en:"Driver", ja:"運転手", ko:"기사" } },
  { id:"pe_teacher", label:"老師", emoji:"🏫", cat:"People", i18n:{ en:"Teacher", ja:"先生", ko:"선생님" } },
  { id:"pe_police", label:"警察", emoji:"👮", cat:"People", i18n:{ en:"Police", ja:"警察", ko:"경찰" } },
  { id:"pe_staff", label:"服務人員", emoji:"ℹ️", cat:"People", i18n:{ en:"Staff", ja:"係の人", ko:"직원" } },
  { id:"pe_interpreter", label:"翻譯員", emoji:"🌐", cat:"People", i18n:{ en:"Interpreter", ja:"通訳", ko:"통역사" } },
  { id:"pe_caregiver", label:"照護員", emoji:"🤲", cat:"People", i18n:{ en:"Caregiver", ja:"介護士", ko:"요양보호사" } },
  { id:"pe_pharmacist", label:"藥師", emoji:"💊", cat:"People", i18n:{ en:"Pharmacist", ja:"薬剤師", ko:"약사" } },
  { id:"pl_home", label:"家裡", emoji:"🏠", cat:"Places", i18n:{ en:"Home", ja:"家", ko:"집" } },
  { id:"pl_shop", label:"店裡", emoji:"🏪", cat:"Places", i18n:{ en:"The shop", ja:"店", ko:"가게" } },
  { id:"pl_hospital", label:"醫院", emoji:"🏥", cat:"Places", i18n:{ en:"Hospital", ja:"病院", ko:"병원" } },
  { id:"pl_clinic", label:"診所", emoji:"🏨", cat:"Places", i18n:{ en:"Clinic", ja:"診療所", ko:"의원" } },
  { id:"pl_pharmacy", label:"藥局", emoji:"💊", cat:"Places", i18n:{ en:"Pharmacy", ja:"薬局", ko:"약국" } },
  { id:"pl_toilet", label:"廁所", emoji:"🚻", cat:"Places", i18n:{ en:"Toilet", ja:"トイレ", ko:"화장실" } },
  { id:"pl_restaurant", label:"餐廳", emoji:"🍽", cat:"Places", i18n:{ en:"Restaurant", ja:"レストラン", ko:"식당" } },
  { id:"pl_station", label:"車站", emoji:"🚉", cat:"Places", i18n:{ en:"Station", ja:"駅", ko:"역" } },
  { id:"pl_car", label:"車上", emoji:"🚗", cat:"Places", i18n:{ en:"In the car", ja:"車の中", ko:"차 안" } },
  { id:"pl_outside", label:"外面", emoji:"🌤", cat:"Places", i18n:{ en:"Outside", ja:"外", ko:"밖" } },
  { id:"pl_airport", label:"機場", emoji:"✈️", cat:"Places", i18n:{ en:"Airport", ja:"空港", ko:"공항" } },
  { id:"pl_parking", label:"停車場", emoji:"🅿️", cat:"Places", i18n:{ en:"Parking", ja:"駐車場", ko:"주차장" } },
  { id:"pl_bank", label:"銀行", emoji:"🏦", cat:"Places", i18n:{ en:"Bank", ja:"銀行", ko:"은행" } },
  { id:"pl_post", label:"郵局", emoji:"📮", cat:"Places", i18n:{ en:"Post office", ja:"郵便局", ko:"우체국" } },
  { id:"pl_school", label:"學校", emoji:"🏫", cat:"Places", i18n:{ en:"School", ja:"学校", ko:"학교" } },
  { id:"pl_library", label:"圖書館", emoji:"📚", cat:"Places", i18n:{ en:"Library", ja:"図書館", ko:"도서관" } },
  { id:"pl_hotel", label:"旅館", emoji:"🏨", cat:"Places", i18n:{ en:"Hotel", ja:"ホテル", ko:"호텔" } },
  { id:"pl_gate", label:"登機門", emoji:"🚪", cat:"Places", i18n:{ en:"Boarding gate", ja:"搭乗口", ko:"탑승구" } },
  { id:"md_sick", label:"不舒服", emoji:"🤕", cat:"Medical", strong:true, i18n:{ en:"Not feeling well", ja:"具合が悪い", ko:"몸이 안 좋아요" } },
  { id:"md_pain_head", label:"頭痛", emoji:"🤯", cat:"Medical", i18n:{ en:"Headache", ja:"頭痛", ko:"두통" } },
  { id:"md_pain_chest", label:"胸口痛", emoji:"💔", cat:"Medical", strong:true, i18n:{ en:"Chest pain", ja:"胸が痛い", ko:"가슴이 아파요" } },
  { id:"md_dizzy", label:"頭暈", emoji:"😵", cat:"Medical", i18n:{ en:"Dizzy", ja:"めまい", ko:"어지러워요" } },
  { id:"md_nausea", label:"想吐", emoji:"🤢", cat:"Medical", i18n:{ en:"Nauseous", ja:"吐き気", ko:"토할 것 같아요" } },
  { id:"md_breath", label:"喘不過氣", emoji:"🫁", cat:"Medical", strong:true, i18n:{ en:"Short of breath", ja:"息苦しい", ko:"숨쉬기 힘들어요" } },
  { id:"md_medicine", label:"需要藥", emoji:"💊", cat:"Medical", i18n:{ en:"Need medicine", ja:"薬がほしい", ko:"약이 필요해요" } },
  { id:"md_hospital", label:"去醫院", emoji:"🚑", cat:"Medical", strong:true, i18n:{ en:"Go to hospital", ja:"病院へ", ko:"병원에 가요" } },
  { id:"md_pressure", label:"量血壓", emoji:"🩺", cat:"Medical", i18n:{ en:"Blood pressure", ja:"血圧を測る", ko:"혈압 측정" } },
  { id:"md_sugar", label:"量血糖", emoji:"🩸", cat:"Medical", i18n:{ en:"Blood sugar", ja:"血糖を測る", ko:"혈당 측정" } },
  { id:"md_allergy", label:"過敏", emoji:"🤧", cat:"Medical", i18n:{ en:"Allergy", ja:"アレルギー", ko:"알레르기" } },
  { id:"md_diabetes", label:"糖尿病", emoji:"🩸", cat:"Medical", i18n:{ en:"Diabetes", ja:"糖尿病", ko:"당뇨병" } },
  { id:"md_heart", label:"心臟不舒服", emoji:"💔", cat:"Medical", strong:true, i18n:{ en:"Heart discomfort", ja:"心臓が苦しい", ko:"심장이 안 좋아요" } },
  { id:"md_fever", label:"發燒", emoji:"🌡", cat:"Medical", i18n:{ en:"Fever", ja:"発熱", ko:"열이 나요" } },
  { id:"md_fall", label:"跌倒", emoji:"🩹", cat:"Medical", strong:true, i18n:{ en:"Fell down", ja:"転んだ", ko:"넘어졌어요" } },
  { id:"md_appointment", label:"預約", emoji:"📅", cat:"Medical", i18n:{ en:"Appointment", ja:"予約", ko:"예약" } },
  { id:"md_insurance", label:"保險卡", emoji:"🪪", cat:"Medical", i18n:{ en:"Insurance card", ja:"保険証", ko:"보험증" } },
  { id:"md_prescription", label:"處方箋", emoji:"📄", cat:"Medical", i18n:{ en:"Prescription", ja:"処方箋", ko:"처방전" } },
  { id:"t_now", label:"現在", emoji:"⏱", cat:"Time", i18n:{ en:"Now", ja:"今", ko:"지금" } },
  { id:"t_later", label:"等一下", emoji:"⏳", cat:"Time", i18n:{ en:"In a moment", ja:"後で", ko:"잠시 후" } },
  { id:"t_morning", label:"早上", emoji:"🌅", cat:"Time", i18n:{ en:"Morning", ja:"朝", ko:"아침" } },
  { id:"t_noon", label:"中午", emoji:"☀️", cat:"Time", i18n:{ en:"Noon", ja:"昼", ko:"점심" } },
  { id:"t_evening", label:"晚上", emoji:"🌙", cat:"Time", i18n:{ en:"Evening", ja:"夜", ko:"저녁" } },
  { id:"t_today", label:"今天", emoji:"📅", cat:"Time", i18n:{ en:"Today", ja:"今日", ko:"오늘" } },
  { id:"t_tomorrow", label:"明天", emoji:"➡️", cat:"Time", i18n:{ en:"Tomorrow", ja:"明日", ko:"내일" } },
  { id:"t_yesterday", label:"昨天", emoji:"⬅️", cat:"Time", i18n:{ en:"Yesterday", ja:"昨日", ko:"어제" } },
  { id:"t_min5", label:"5 分鐘", emoji:"5️⃣", cat:"Time", i18n:{ en:"5 min", ja:"5分", ko:"5분" } },
  { id:"t_min10", label:"10 分鐘", emoji:"🔟", cat:"Time", i18n:{ en:"10 min", ja:"10分", ko:"10분" } },
  { id:"t_min30", label:"30 分鐘", emoji:"🕧", cat:"Time", i18n:{ en:"30 min", ja:"30分", ko:"30분" } },
  { id:"t_hour1", label:"1 小時", emoji:"🕐", cat:"Time", i18n:{ en:"1 hour", ja:"1時間", ko:"1시간" } },
  { id:"t_before", label:"之前", emoji:"⬅️", cat:"Time", i18n:{ en:"Before", ja:"前", ko:"전" } },
  { id:"t_after", label:"之後", emoji:"➡️", cat:"Time", i18n:{ en:"After", ja:"後", ko:"후" } },
  { id:"t_medicine_time", label:"吃藥時間", emoji:"💊", cat:"Time", i18n:{ en:"Medicine time", ja:"薬の時間", ko:"약 먹을 시간" } },
  { id:"t_checkout", label:"退房時間", emoji:"🏨", cat:"Time", i18n:{ en:"Check-out time", ja:"チェックアウト", ko:"체크아웃 시간" } },
  { id:"q_where", label:"在哪裡？", emoji:"📍", cat:"Questions", i18n:{ en:"Where?", ja:"どこ？", ko:"어디예요?" } },
  { id:"q_when", label:"什麼時候？", emoji:"🕒", cat:"Questions", i18n:{ en:"When?", ja:"いつ？", ko:"언제예요?" } },
  { id:"q_how", label:"怎麼做？", emoji:"❓", cat:"Questions", i18n:{ en:"How?", ja:"どうやって？", ko:"어떻게 해요?" } },
  { id:"q_can", label:"可以嗎？", emoji:"✅", cat:"Questions", i18n:{ en:"May I?", ja:"いい？", ko:"괜찮아요?" } },
  { id:"q_have", label:"有嗎？", emoji:"🔎", cat:"Questions", i18n:{ en:"Do you have it?", ja:"ある？", ko:"있어요?" } },
  { id:"q_price", label:"多少錢？", emoji:"💵", cat:"Questions", i18n:{ en:"How much?", ja:"いくら？", ko:"얼마예요?" } },
  { id:"q_again", label:"可以再說一次嗎？", emoji:"🔁", cat:"Questions", i18n:{ en:"Say that again?", ja:"もう一度いい？", ko:"다시 말해 줄래요?" } },
  { id:"q_help", label:"可以幫我嗎？", emoji:"🤲", cat:"Questions", i18n:{ en:"Can you help me?", ja:"手伝ってくれる？", ko:"도와줄 수 있어요?" } },
  { id:"q_toilet", label:"廁所在哪裡？", emoji:"🚻", cat:"Questions", i18n:{ en:"Where's the toilet?", ja:"トイレはどこ？", ko:"화장실 어디예요?" } },
  { id:"q_exit", label:"出口在哪裡？", emoji:"🚪", cat:"Questions", i18n:{ en:"Where's the exit?", ja:"出口はどこ？", ko:"출구 어디예요?" } },
  { id:"q_counter", label:"服務台在哪裡？", emoji:"ℹ️", cat:"Questions", i18n:{ en:"Where's the counter?", ja:"受付はどこ？", ko:"안내데스크 어디예요?" } },
  { id:"q_gate", label:"登機門在哪裡？", emoji:"✈️", cat:"Questions", i18n:{ en:"Where's the gate?", ja:"搭乗口はどこ？", ko:"탑승구 어디예요?" } },
  { id:"q_appointment", label:"要等多久？", emoji:"⏳", cat:"Questions", i18n:{ en:"How long is the wait?", ja:"どのくらい待つ？", ko:"얼마나 기다려요?" } },
  { id:"q_english", label:"可以說中文嗎？", emoji:"🌐", cat:"Questions", i18n:{ en:"Do you speak Chinese?", ja:"中国語話せる？", ko:"중국어 하세요?" } },
  { id:"e_thanks", label:"謝謝", emoji:"🙏", cat:"Emotions", i18n:{ en:"Thank you", ja:"ありがとう", ko:"감사합니다" } },
  { id:"e_sorry", label:"抱歉", emoji:"😅", cat:"Emotions", i18n:{ en:"Sorry", ja:"ごめんなさい", ko:"죄송해요" } },
  { id:"e_welcome", label:"歡迎光臨", emoji:"😊", cat:"Emotions", i18n:{ en:"Welcome", ja:"いらっしゃいませ", ko:"어서 오세요" } },
  { id:"e_happy", label:"開心", emoji:"😊", cat:"Emotions", i18n:{ en:"Happy", ja:"うれしい", ko:"기뻐요" } },
  { id:"e_worried", label:"擔心", emoji:"😟", cat:"Emotions", i18n:{ en:"Worried", ja:"心配", ko:"걱정돼요" } },
  { id:"e_angry", label:"生氣", emoji:"😠", cat:"Emotions", i18n:{ en:"Angry", ja:"怒ってる", ko:"화나요" } },
  { id:"e_tired", label:"很累", emoji:"😮‍💨", cat:"Emotions", i18n:{ en:"Tired", ja:"疲れた", ko:"피곤해요" } },
  { id:"e_scared", label:"害怕", emoji:"😨", cat:"Emotions", i18n:{ en:"Scared", ja:"こわい", ko:"무서워요" } },
  { id:"e_good", label:"很好", emoji:"👍", cat:"Emotions", i18n:{ en:"Good", ja:"いい", ko:"좋아요" } },
  { id:"e_bad", label:"不好", emoji:"👎", cat:"Emotions", i18n:{ en:"Not good", ja:"よくない", ko:"안 좋아요" } },
  { id:"e_comfort", label:"沒關係", emoji:"🤝", cat:"Emotions", i18n:{ en:"It's OK", ja:"大丈夫", ko:"괜찮아요" } },
  { id:"e_confused", label:"我聽不懂", emoji:"😕", cat:"Emotions", i18n:{ en:"I don't understand", ja:"わからない", ko:"못 알아듣겠어요" } },
  { id:"e_nervous", label:"緊張", emoji:"😰", cat:"Emotions", i18n:{ en:"Nervous", ja:"緊張してる", ko:"긴장돼요" } },
  { id:"e_lonely", label:"孤單", emoji:"🥺", cat:"Emotions", i18n:{ en:"Lonely", ja:"さびしい", ko:"외로워요" } },
  { id:"e_safe", label:"安心", emoji:"😌", cat:"Emotions", i18n:{ en:"Relieved", ja:"安心", ko:"안심돼요" } },
  { id:"e_hurry", label:"很急", emoji:"🏃", cat:"Emotions", i18n:{ en:"In a hurry", ja:"急いでる", ko:"급해요" } },
  { id:"g_help", label:"救命", emoji:"🆘", cat:"Emergency", strong:true, i18n:{ en:"Help!", ja:"助けて", ko:"살려주세요" } },
  { id:"g_family", label:"找家人", emoji:"📞", cat:"Emergency", strong:true, i18n:{ en:"Get my family", ja:"家族を呼んで", ko:"가족을 불러 주세요" } },
  { id:"g_sick", label:"不舒服", emoji:"🤕", cat:"Emergency", strong:true, i18n:{ en:"Not feeling well", ja:"具合が悪い", ko:"몸이 안 좋아요" } },
  { id:"g_police", label:"報警", emoji:"🚓", cat:"Emergency", strong:true, i18n:{ en:"Call the police", ja:"警察を呼んで", ko:"경찰 불러 주세요" } },
  { id:"g_ambulance", label:"叫救護車", emoji:"🚑", cat:"Emergency", strong:true, i18n:{ en:"Call an ambulance", ja:"救急車を呼んで", ko:"구급차 불러 주세요" } },
  { id:"g_fall", label:"跌倒了", emoji:"🩹", cat:"Emergency", strong:true, i18n:{ en:"I fell", ja:"転んだ", ko:"넘어졌어요" } },
  { id:"g_choke", label:"噎到", emoji:"🫢", cat:"Emergency", strong:true, i18n:{ en:"Choking", ja:"のどに詰まった", ko:"목에 걸렸어요" } },
  { id:"g_fire", label:"火災", emoji:"🔥", cat:"Emergency", strong:true, i18n:{ en:"Fire", ja:"火事", ko:"불이야" } },
  { id:"g_lost", label:"迷路", emoji:"🧭", cat:"Emergency", strong:true, i18n:{ en:"Lost", ja:"道に迷った", ko:"길을 잃었어요" } },
  { id:"g_cant_breathe", label:"不能呼吸", emoji:"🫁", cat:"Emergency", strong:true, i18n:{ en:"Can't breathe", ja:"息ができない", ko:"숨을 못 쉬어요" } },
  { id:"g_seizure", label:"抽搐", emoji:"⚠️", cat:"Emergency", strong:true, i18n:{ en:"Seizure", ja:"けいれん", ko:"경련" } },
  { id:"g_allergy", label:"嚴重過敏", emoji:"🤧", cat:"Emergency", strong:true, i18n:{ en:"Severe allergy", ja:"重いアレルギー", ko:"심한 알레르기" } },
  { id:"g_chest", label:"胸痛", emoji:"💔", cat:"Emergency", strong:true, i18n:{ en:"Chest pain", ja:"胸が痛い", ko:"가슴 통증" } },
];

export const CURRENCIES = [
  { code:"NTD", symbol:"NT$", name:"新台幣" },
  { code:"USD", symbol:"US$", name:"美元" },
  { code:"JPY", symbol:"¥", name:"日圓" },
  { code:"KRW", symbol:"₩", name:"韓圜" },
  { code:"CNY", symbol:"¥", name:"人民幣" },
  { code:"EUR", symbol:"€", name:"歐元" },
];


/** 卡片在指定語言下的詞面；查無退回繁中原文。 */
export function labelIn(item, lang) {
  if (!item) return "";
  const base = (lang || "zh-TW").split("-")[0];
  if (base === "zh") return item.label;
  return (item.i18n && item.i18n[base]) || item.label;
}
